Repository bbc/genie, pull requests merged in 2020-02, with the labels that each got.

#148 CGPROD 2134 Safe Area Min Width
  src/core/layout/layout.js
  src/core/layout/safe-area.js
  test/core/layout/layout.test.js
  test/core/layout/safe-area.test.js
Labels: Ready for Review 🔜

#152 CGPROD-2108_Text-on-GEL-Buttons
  src/components/select.js
  src/core/layout/button-factory.js
  src/core/layout/grid/cell.js
  src/core/layout/grid/grid.js
  test/components/select.test.js
  test/core/layout/grid/cell.test.js
  test/core/layout/grid/grid.test.js
  themes/default/asset-packs/character-select.json
  themes/default/config/character-select.json5
Labels: Ready for Review 🔜

#154 [CGPROD-2132] Countup audio changes for low and high scores
  src/components/results/results-countup.js
  test/components/results/results-countup.test.js
  themes/default/config/results.json5
Labels: Bug 🐛, Ready for Review 🔜, ✨ Enhancement ✨

#155 Cgprod 2122 select hover link
  src/components/results/results-screen.js
  src/components/select.js
  src/components/select/add-events.js
  src/components/select/select-screen.js
  src/components/select/single-item-mode.js
  src/components/select/titles.js
  src/core/helpers/element-bounding.js
  src/core/layout/button-factory.js
  src/core/layout/gel-button.js
  src/core/layout/gel-game-objects.js
  src/core/layout/gel-group.js
  src/core/layout/grid/cell.js
  src/core/layout/grid/grid.js
  src/core/layout/safe-area.js
  src/core/state.js
  src/main.js
  test/components/results/results-screen.test.js
  test/components/select/add-events.test.js
  test/components/select/select-screen.test.js
  test/components/select/single-item-mode.test.js
  test/core/helpers/element-bounding.test.js
  test/core/layout/button-factory.test.js
  test/core/layout/gel-button.test.js
  test/core/layout/grid/cell.test.js
  test/core/layout/grid/grid.test.js
  test/core/layout/safe-area.test.js
  test/main.test.js
  themes/default/asset-packs/character-select.json
  themes/default/characters/title_drop.png
  themes/default/config/character-select.json5
Labels: Ready for Review 🔜, WARNING BIG PR 🐳

#165 [CGPROD-2152] Move starter pack docs into core
  dev/docs/build.md
  dev/docs/coding-guidelines.md
  dev/docs/navigation.md
  dev/docs/notes-on-genie-core.md
  docs/GEL_UI_EXAMPLE.sketch
  docs/build.md
  docs/development/accessibilify.md
  docs/development/achievements.md
  docs/development/automated-tests.md
  docs/development/brim.md
  docs/development/code-restrictions.md
  docs/development/data-storage.md
  docs/development/event-bus.md
  docs/development/gameplay-component.md
  docs/development/gmi.md
  docs/development/phaser-terminology.md
  docs/development/results-screen/images/results-backdrops.png
  docs/development/results-screen/images/results-objects.png
  docs/development/results-screen/images/results-rows.png
  docs/development/results-screen/results-audio.md
  docs/development/results-screen/results-countup.md
  docs/development/results-screen/results-sprite.md
  docs/development/results-screen/results-start.md
  docs/development/results-screen/results-text.md
  docs/development/results-screen/results-transitions.md
  docs/development/select-screen.md
  docs/development/settings.md
  docs/development/stats.md
  docs/getting-started.md
  docs/resources/gamesqaprocess.png
  docs/resources/genieCertDetail.pdf
  docs/resources/geniecertoutline.pdf
  docs/resources/supportedDevices.pdf
  docs/resources/testplantemplate.doc
  docs/tech-review-tool.md
  docs/testing.md
  docs/theming.md
Labels: Documentation 📙, Ready for Review 🔜, WARNING BIG PR 🐳

#170 NOTICKET refactors
  dev/dev.css
  src/core/accessibility/accessibilify.js
  src/core/debug/debug.js
  test/core/debug/debug.test.js
  themes/default/characters/1.png
  themes/default/characters/10.png
  themes/default/characters/2.png
  themes/default/characters/3.png
  themes/default/characters/4.png
  themes/default/characters/5.png
  themes/default/characters/6.png
  themes/default/characters/7.png
  themes/default/characters/8.png
  themes/default/characters/9.png
  themes/default/config/character-select.json5
Labels: Ready for Review 🔜

#177 CGPROD-2157_Select-Subtitle-Text-Is-Aligned
  src/components/select/select-screen.js
  src/components/select/titles.js
  test/components/select/select-screen.test.js
  test/components/select/titles.test.js
  themes/default/config/character-select.json5
Labels: Ready for Review 🔜

#176 Cgprod 2112 single item pause
  src/components/select/select-screen.js
  src/components/select/single-item-mode.js
  src/core/layout/button-factory.js
  src/core/layout/grid/grid.js
  src/core/layout/layout.js
  src/core/screen.js
  test/components/select/select-screen.test.js
  test/components/select/single-item-mode.test.js
  test/core/layout/button-factory.test.js
  test/core/layout/grid/grid.test.js
  test/core/layout/layout.test.js
  test/core/screen.test.js
  test/game.test.js
Labels: Ready for Review 🔜

#187 Noticket debug draw improvements
  .eslintrc
  src/core/debug/debug.js
  src/core/debug/layout-debug-draw.js
  src/core/screen.js
  test/core/debug/debug.test.js
  test/core/debug/layout-debug-draw.test.js
  themes/default/config/home.json5
  themes/default/gel/debug/FF0030-hatch.png
  themes/default/gel/debug/FFCC00-hatch.png
  themes/default/gel/gel-pack.json
  themes/default/shared/title.png
Labels: Ready for Review 🔜

#189 GPROD-2218_Select-Screen-Tabbing-Animation-Bug
  src/core/layout/grid/grid.js
  test/core/layout/grid/grid.test.js
Labels: Ready for Review 🔜

#194 CGPROD-2211: Pause Button Audio Bug
  src/core/layout/gel-button.js
  test/core/layout/gel-button.test.js
Labels: Bug 🐛
