Repository bbc/genie, pull requests merged in 2021-01, with the labels that each got.

#358 [CGPROD-2962] fix buttonsRight config
  src/components/shop/confirm.js
  src/components/shop/menu-buttons.js
  test/components/shop/confirm.test.js
  test/components/shop/menu-buttons.test.js
Labels: Ready for Review 🔜

#366 CGPROD 3002 Phaser Update
  CHANGELOG.md
  lib/SpinePlugin.min.js
  lib/rexbbcodetextplugin.min.js
  lib/rexuiplugin.min.js
  package-lock.json
  package.json
  src/core/loader/phaser-defaults/get-default-plugins.js
  src/main.js
  test/components/results/results-sprite.test.js
  test/core/layout/gel-button.test.js
  test/core/layout/scrollable-list/scrollable-list.test.js
  test/core/loader/phaser-defaults/get-default-plugins.test.js
Labels: Ready for Review 🔜

#367 NOTICKET debug collection Fixes
  src/core/collections.js
  src/core/debug/debug-mode.js
  src/core/debug/debug-screens.js
  src/core/loader/load-collections.js
  src/core/loader/loader.js
  test/core/collections.test.js
  test/core/debug/debug-mode.test.js
  test/core/debug/debug-screens.test.js
  test/core/loader/load-collections.test.js
Labels: Genie 🧞‍♀️, Ready for Review 🔜

#375 NOTICKET Roll Back Phaser
  CHANGELOG.md
  lib/SpinePlugin.min.js
  lib/rexuiplugin.min.js
  package-lock.json
  package.json
  src/core/loader/phaser-defaults/get-default-plugins.js
  test/components/results/results-sprite.test.js
Labels: Genie 🧞‍♀️
