Repository bbc/genie, pull requests merged in 2021-03, with the labels that each got.

#404 NOTICKET DOM Elements
  cypress/integration/shop_spec.js
  src/components/game.js
  src/components/shop/scrollable-list/scrollable-list-buttons.js
  src/components/shop/scrollable-list/scrollable-list-handlers.js
  src/components/shop/scrollable-list/scrollable-list.js
  src/components/shop/scrollable-list/scrollable-panel.js
  src/components/shop/shop-list-screen.js
  test/components/shop/scrollable-list/scrollable-list-handlers.test.js
  test/components/shop/scrollable-list/scrollable-list.test.js
  test/components/shop/scrollable-list/scrollable-panel.test.js
  test/components/shop/shop-list-screen.test.js
Labels: Ready for Review 🔜

#427 CGPROD 3115 - W key crash
  src/components/shop/scrollable-list/scrollable-panel.js
  test/components/shop/scrollable-list/scrollable-panel.test.js
Labels: Genie 🧞‍♀️, Ready for Review 🔜

#426 CGPROD 3117 debug confirm backgrounds
  debug/assets.json
  debug/assets/shop/equip.mp4
  debug/assets/shop/till.mp4
  debug/assets/shop/unequip.mp4
  debug/assets/shop/use.mp4
  debug/examples/shop-consumables-confirm.json5
  debug/examples/shop-equippables-confirm.json5
Labels: Genie 🧞‍♀️, Ready for Review 🔜

#428 Cgprod 3098 stats issues
  src/components/shop/menu-buttons.js
  src/components/shop/scrollable-list/scrollable-list-handlers.js
  src/components/shop/scrollable-list/scrollable-list.js
  src/components/shop/shop-list-screen.js
  src/components/shop/transact.js
  test/components/shop/menu-buttons.test.js
  test/components/shop/scrollable-list/scrollable-list.test.js
  test/components/shop/shop-list-screen.test.js
  test/components/shop/transact.test.js
Labels: Genie 🧞‍♀️, Ready for Review 🔜

#425 CGPROD-3081 Scrollable List Empty State
  debug/examples/shop-consumables-list.json5
  debug/examples/shop-equippables-list.json5
  src/components/shop/scrollable-list/scrollable-list.js
  test/components/shop/scrollable-list/scrollable-list.test.js
  themes/default/shop-list/config.json5
Labels: ✨ Enhancement ✨

#434 Cgprod 3125 collection issue
  cypress/support/statConfig.js
  src/components/shop/confirm.js
  src/components/shop/confirm/confirm-buttons.js
  src/components/shop/confirm/confirm-resize.js
  src/components/shop/confirm/confirm.js
  src/components/shop/confirm/item-checks.js
  src/components/shop/confirm/item-view.js
  src/components/shop/confirm/prompt-text.js
  src/components/shop/menu-buttons.js
  src/components/shop/scrollable-list/button-overlays.js
  src/components/shop/scrollable-list/scrollable-list-buttons.js
  src/components/shop/scrollable-list/scrollable-list.js
  src/components/shop/shop-confirm-screen.js
  src/core/collections.js
  src/core/layout/text.js
  src/core/titles.js
  test/components/shop/confirm/confirm-buttons.test.js
  test/components/shop/confirm/confirm-resize.test.js
  test/components/shop/confirm/confirm.test.js
  test/components/shop/confirm/item-checks.test.js
  test/components/shop/confirm/item-view.test.js
  test/components/shop/confirm/prompt-text.test.js
  test/components/shop/menu-buttons.test.js
  test/components/shop/scrollable-list/button-overlays.test.js
  test/components/shop/scrollable-list/scrollable-list.test.js
  test/components/shop/shop-confirm-screen.test.js
  test/core/collections.test.js
  test/core/layout/text-elem.test.js
  test/core/titles.test.js
  themes/default/collections/inventory.json5
  themes/default/shop-confirm/assets/half_panel.png
  themes/default/shop-confirm/config.json5
  themes/default/shop-menu/config.json5
Labels: Genie 🧞‍♀️, Ready for Review 🔜

#438 CGPROD 3121 confirm backgrounds
  src/components/game.js
  src/components/shop/confirm/confirm-resize.js
  src/components/shop/confirm/confirm.js
  src/components/shop/confirm/item-view.js
  src/components/shop/menu.js
  src/components/shop/shop-confirm-screen.js
  src/components/shop/shop-menu-screen.js
  test/components/shop/confirm/confirm-resize.test.js
  test/components/shop/confirm/confirm.test.js
  test/components/shop/confirm/item-view.test.js
  test/components/shop/menu-buttons.test.js
  test/components/shop/menu.test.js
  test/components/shop/scrollable-list/button-overlays.test.js
  test/components/shop/scrollable-list/get-button-state.test.js
  test/components/shop/scrollable-list/scrollable-list-buttons.test.js
  test/components/shop/scrollable-list/scrollable-list-handlers.test.js
  test/components/shop/scrollable-list/scrollable-list.test.js
  test/components/shop/shop-confirm-screen.test.js
  test/components/shop/shop-layout.test.js
  test/components/shop/shop-list-screen.test.js
  test/components/shop/shop-menu-screen.test.js
  themes/default/shop-confirm/assets.json
  themes/default/shop-confirm/assets/half-panel.png
  themes/default/shop-confirm/assets/half_panel.png
  themes/default/shop-confirm/assets/item-background.png
  themes/default/shop-confirm/assets/title-background.png
  themes/default/shop-confirm/config.json5
  themes/default/shop-list/assets.json
  themes/default/shop-list/assets/currency-small.png
  themes/default/shop-list/assets/item-block.png
  themes/default/shop-list/assets/item-panel.png
  themes/default/shop-list/assets/lock-icon.png
  themes/default/shop-list/assets/menu-button-icon.png
  themes/default/shop-list/assets/title-background.png
  themes/default/shop-list/assets/wood-panel.png
  themes/default/shop-menu/assets.json
  themes/default/shop-menu/assets/balance-background.png
  themes/default/shop-menu/assets/balance-icon.png
  themes/default/shop-menu/assets/green-button.png
  themes/default/shop-menu/assets/magic-shop-bg.png
  themes/default/shop-menu/assets/title-background.png
Labels: Ready for Review 🔜
