Repository bbc/genie, pull requests merged in 2021-02, with the labels that each got.

#382 [CGPROD-2946] - RC vis changes
  debug/examples/shop-demo-shop.json5
  debug/examples/shop.json5
  src/components/select/titles.js
  src/components/shop/balance-ui.js
  src/components/shop/confirm.js
  src/components/shop/menu-buttons.js
  src/components/shop/shop-layout.js
  src/core/layout/scrollable-list/button-overlays.js
  src/core/layout/text-elem.js
  test/components/select/titles.test.js
  test/components/shop/balance-ui.test.js
  test/components/shop/confirm.test.js
  test/components/shop/menu-buttons.test.js
  test/components/shop/shop-layout.test.js
  test/core/layout/scrollable-list/button-overlays.test.js
  test/core/layout/text-elem.test.js
Labels: Ready for Review 🔜

#383 CGPROD 3000 NinePatch
  debug/examples/shop.json5
  lib/rexninepatchplugin.min.js
  package-lock.json
  package.json
  src/components/shop/background.js
  src/components/shop/confirm.js
  src/components/shop/menu.js
  src/components/shop/shop-layout.js
  src/components/shop/shop.js
  src/core/layout/scrollable-list/backgrounds.js
  src/core/layout/scrollable-list/scrollable-list.js
  src/core/loader/phaser-defaults/get-default-plugins.js
  test/components/shop/background.test.js
  test/components/shop/confirm.test.js
  test/components/shop/shop-layout.test.js
  test/components/shop/shop.test.js
  test/core/layout/scrollable-list/backgrounds.test.js
  test/core/layout/scrollable-list/scrollable-list.test.js
  test/core/loader/phaser-defaults/get-default-plugins.test.js
  themes/default/shop/config.json5
Labels: Genie 🧞‍♀️, Ready for Review 🔜

#384 [CGPROD-2947] shop functions as overlay
  debug/examples/shop-demo-shop.json5
  debug/examples/shop.json5
  docs/development/shop-component/adding-shop.md
  src/components/shop/shop.js
  test/components/shop/shop.test.js
  themes/default/items/inventory.json5
  themes/default/shop/config.json5
Labels: Ready for Review 🔜

#390 [CGPROD-2944] Equippable items
  .prettierrc
  collections-plan.md
  debug/examples/shop-demo-shop.json5
  debug/examples/shop.json5
  debug/items/debug-armoury.json5
  debug/items/debug-demo-hats.json5
  debug/items/debug-demo-inventory.json5
  debug/items/debug-game-items.json5
  jest.config.js
  src/components/shop/background.js
  src/components/shop/balance-ui.js
  src/components/shop/confirm.js
  src/components/shop/menu-buttons.js
  src/components/shop/scrollable-list/backgrounds.js
  src/components/shop/scrollable-list/button-overlays.js
  src/components/shop/scrollable-list/scrollable-list-buttons.js
  src/components/shop/scrollable-list/scrollable-list-handlers.js
  src/components/shop/scrollable-list/scrollable-list.js
  src/components/shop/shop.js
  src/components/shop/transact.js
  test/components/shop/background.test.js
  test/components/shop/balance-ui.test.js
  test/components/shop/confirm.test.js
  test/components/shop/menu-buttons.test.js
  test/components/shop/scrollable-list/backgrounds.test.js
  test/components/shop/scrollable-list/button-overlays.test.js
  test/components/shop/scrollable-list/scrollable-list-buttons.test.js
  test/components/shop/scrollable-list/scrollable-list-handlers.test.js
  test/components/shop/scrollable-list/scrollable-list.test.js
  test/components/shop/shop.test.js
  test/components/shop/transact.test.js
Labels: WARNING BIG PR 🐳, Work In Prog 👷🏿‍♀️👷🏽‍♀️👷🏽‍♂️👷🏻‍♀️👷🏿‍♂️👷🏻‍♂️

#396 [CGPROD-2812] shop stats
  src/components/shop/menu-buttons.js
  src/components/shop/shop.js
  src/components/shop/transact.js
  test/components/shop/menu-buttons.test.js
  test/components/shop/shop.test.js
  test/components/shop/transact.test.js
Labels: Ready for Review 🔜
